import type { Metadata } from "next";
import localFont from 'next/font/local'
import "./globals.css";
 
const myFont = localFont({
  src: "../public/fonts/PPNeueMontreal-Book.otf", 
  variable: "--font-pp-editorial",
  weight: "400",
  style: "normal",
  display: "swap",
});

export const metadata: Metadata = {
  title: "jojazpeitia",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${myFont.variable}`}>
      <body>
        {children}
      </body>
    </html>
  );
}
